const IDIOMS_MAP = {
    "piece of cake": "çocuk oyuncağı / çok kolay",
    "break a leg": "iyi şanslar (sahne öncesi)",
    "under the weather": "halsiz / biraz hasta",
    "call it a day": "bugünlük bu kadar demek / bırakmak",
    "bite the bullet": "dişini sıkmak / acıya katlanmak",
    "once in a blue moon": "ayda yılda bir / çok nadir",
    "cost an arm and a leg": "bir servete mal olmak / çok pahalı",
    "no pain no gain": "emek olmadan yemek olmaz",
    "kill two birds with one stone": "bir taşla iki kuş vurmak",
    "break the ice": "buzları eritmek (ortamı yumuşatmak)",
    "miss the boat": "fırsatı kaçırmak",
    "pull someone's leg": "birisiyle kafa bulmak / şaka yapmak",
    "spill the beans": "ağzındaki baklayı çıkarmak / sırrı açıklamak",
    "hit the hay": "kafayı vurup yatmak / uyumaya gitmek",
    "beat around the bush": "lafı dolandırmak",
    "better late than never": "geç olsun da güç olmasın",
    "blessing in disguise": "her işte bir hayır vardır",
    "cry over spilt milk": "son pişmanlık fayda etmez",
    "barking up the wrong tree": "yanlış kapıyı çalmak / yanlış yerde aramak",
    "let the cat out of the bag": "sırrı ağzından kaçırmak",
    "piece of mind": "iç huzuru",
    "give someone a piece of your mind": "birine ağzının payını vermek",
    "apple of my eye": "gözümün nuru",
    "bread and butter": "geçim kaynağı / asıl iş",
    "cool as a cucumber": "soğukkanlı / aşırı sakin",
    "couch potato": "televizyon bağımlısı / miskin",
    "cup of tea": "harcı olmak / ilgi alanı",
    "it's not my cup of tea": "bana göre değil / ilgi alanım değil",
    "egg on your face": "rezil olmak",
    "full of beans": "enerji dolu",
    "hard nut to crack": "çetin ceviz",
    "in a nutshell": "özetle",
    "take it with a grain of salt": "ihtiyatla karşılamak / şüpheyle bakmak",
    "walk on eggshells": "yumurta küfesi taşımak / çok dikkatli davranmak",
    "burn the midnight oil": "gece gündüz çalışmak",
    "cut to the chase": "sadede gelmek",
    "get a grip": "kendine gelmek",
    "hands down": "şüphesiz / kesinlikle",
    "hang in there": "dişini sık / pes etme",
    "jump on the bandwagon": "modaya uymak / çoğunluğa katılmak",
    "keep your chin up": "başını dik tut / moralini bozma",
    "let sleeping dogs lie": "uyuyan devleri uyandırmama / kurcalamamak",
    "off the hook": "paçayı kurtarmak",
    "on the ball": "işini bilmek / uyanık olmak",
    "set the record straight": "yanlışı düzeltmek / gerçeği açıklamak",
    "steal someone's thunder": "birinin rolünü çalmak / başarısını gölgelemek",
    "straight from the horse's mouth": "birinci ağızdan / yetkili birinden",
    "the elephant in the room": "görmezden gelinen büyük sorun",
    "through thick and thin": "iyi günde kötü günde",
    "under the sun": "dünya üzerinde / mevcut olan her şey",
    "up in the air": "havada kalmış / belirsiz",
    "wild goose chase": "boşuna kürek çekmek / beyhude çaba",
    "your guess is as good as mine": "ben de senin kadar biliyorum",
    "at the drop of a hat": "dünden razı / hemen o anda",
    "ball is in your court": "top sende / karar senin",
    "best of both worlds": "bir taşla iki kuş / her iki durumun avantajı",
    "hit the nail on the head": "tam üstüne basmak / tam isabet",
    "look before you leap": "sonunu düşünen kahraman olamaz (tedbirli ol)",
    "on thin ice": "tehlikeli sularda yüzmek",
    "play hard to get": "naza çekmek",
    "see eye to eye": "aynı fikirde olmak",
    "sit on the fence": "tarafsız kalmak / kararsız olmak",
    "the last straw": "bardağı taşıran son damla",
    "the whole nine yards": "elde ne varsa / her şeyiyle",
    "wrap your head around something": "aklı ermek / kavramak",
    "feel blue": "hüzünlü hissetmek",
    "out of the blue": "aniden / damdan düşer gibi",
    "black sheep": "aykırı tip / ailenin yüz karası",
    "green thumb": "bahçecilik yeteneği",
    "silver lining": "kötü durumdaki iyi taraf",
    "white lie": "zararsız yalan / pembe yalan",
    "bolt from the blue": "beklenmedik olay / şok edici gelişme",
    "born with a silver spoon": "ağzında gümüş kaşıkla doğmak / şanslı doğmak",
    "catch someone red-handed": "suçüstü yakalamak",
    "golden opportunity": "altın fırsat",
    "in the red": "borçlu durumda olmak / zararda olmak",
    "once in a blue moon": "kırk yılda bir",
    "roll out the red carpet": "krallar gibi karşılamak / büyük hürmet göstermek",
    "see red": "öfkeden gözü dönmek",
    "tickled pink": "mutluluktan havalara uçmak",
    "true colors": "gerçek yüzü",
    "yellow-bellied": "korkak / tabansız",
    "actions speak louder than words": "ayinesi iştir kişinin lafa bakılmaz",
    "add fuel to the fire": "yangına körükle gitmek",
    "all ears": "can kulağıyla dinlemek",
    "apple of Discord": "nifak tohumu",
    "arm to the teeth": "tepeden tırnağa silahlanmak",
    "as blind as a bat": "zifiri kör",
    "as busy as a bee": "arı gibi çalışkan",
    "as cold as ice": "buz gibi soğuk",
    "as free as a bird": "kuşlar gibi hür",
    "as light as a feather": "kuş tüyü gibi hafif",
    "as quiet as a mouse": "süt dökmüş kedi gibi sessiz",
    "back to square one": "en başa dönmek",
    "barking dogs seldom bite": "havlayan köpek ısırmaz",
    "be in hot water": "başı dertte olmak",
    "be in two minds": "iki arada bir derede kalmak",
    "be on the same page": "aynı fikirde olmak",
    "behind someone's back": "birinin arkasından iş çevirmek",
    "between the devil and the deep blue sea": "iki ucu boklu değnek",
    "birds of a feather flock together": "tencere yuvarlanmış kapağını bulmuş",
    "blow one's own trumpet": "kendini övmek",
    "break someone's heart": "birinin kalbini kırmak",
    "bring home the bacon": "eve ekmek getirmek",
    "burn bridges": "köprüleri yakmak",
    "bury the hatchet": "baltaları gömmek (barışmak)",
    "butterflies in one's stomach": "etekleri zil çalmak (heyecandan)",
    "by the skin of one's teeth": "ucu ucuna / kıl payı kurtulmak",
    "cannot judge a book by its cover": "görünüşe aldanmamak gerek",
    "change of heart": "fikir değiştirmek",
    "chicken out": "korkup vazgeçmek",
    "clear the air": "ortamı yumuşatmak / yanlış anlamaları gidermek",
    "close but no cigar": "yaklaştın ama olmadı",
    "crocodile tears": "timsah gözyaşları",
    "cross that bridge when you come to it": "dereyi görmeden paçaları sıvamamak",
    "curiosity killed the cat": "fazla merak iyi değildir",
    "cut corners": "kolaya kaçmak / masraftan kaçınmak",
    "don't count your chickens before they hatch": "dereyi görmeden paçayı sıvama",
    "don't put all your eggs in one basket": "tüm her şeyini tek bir şeye yatırma",
    "down to earth": "ayakları yere basan / gerçekçi / mütevazı",
    "drink like a fish": "sünger gibi içmek",
    "drive someone up the wall": "birini çileden çıkarmak",
    "easy come, easy go": "haydan gelen huya gider",
    "eat like a horse": "kurt gibi acıkmak / çok yemek",
    "every dog has its day": "gün doğmadan neler doğar (şans herkese bir gün güler)",
    "face the music": "sonuçlarına katlanmak",
    "fair-weather friend": "iyi gün dostu",
    "fall in love": "aşık olmak",
    "fish out of water": "sudan çıkmış balık",
    "get cold feet": "son anda tırsmak / korkup vazgeçmek",
    "get out of hand": "kontrolden çıkmak",
    "get someone's goat": "birini damarına basmak / sinirlendirmek",
    "give someone the cold shoulder": "birine soğuk davranmak / yüz vermemek",
    "go Dutch": "alman usulü ödemek",
    "go with the flow": "akışına bırakmak",
    "green-eyed monster": "kıskançlık",
    "have a bone to pick with someone": "biriyle görülecek bir hesabı olmak",
    "have a heart of gold": "altın gibi bir kalbi olmak",
    "have bigger fish to fry": "yapacak daha önemli işleri olmak",
    "head over heels": "sırılsıklam (aşık)",
    "hit the roof": "tepesi atmak / çok sinirlenmek",
    "hold your horses": "biraz dur bakalım / acele etme",
    "in the same boat": "aynı gemide olmak",
    "it's raining cats and dogs": "bardaktan boşalırcasına yağmak",
    "keep an eye on": "göz kulak olmak",
    "keep one's fingers crossed": "şans dilemek",
    "kill the goose that lays the golden eggs": "altın yumurtlayan tavuğu kesmek",
    "let someone down": "birini yarı yolda bırakmak / hayal kırıklığına uğratmak",
    "look like a million dollars": "parıl parıl parlamak / harika görünmek",
    "lose one's cool": "soğukkanlılığını kaybetmek",
    "make a mountain out of a molehill": "pireyi deve yapmak",
    "make ends meet": "iki yakasını bir araya getirmek",
    "on Cloud Nine": "havalarda uçmak / çok mutlu olmak",
    "paint the town red": "felekten bir gece çalmak",
    "piece of the pie": "pastadan pay almak",
    "play with fire": "ateşle oynamak",
    "put one's foot in it": "pot kırmak / ayağını yorganına göre uzatmamak",
    "raining cats and dogs": "bardaktan boşalırcasına yağmur yağması",
    "ring a bell": "tanıdık gelmek / bir şeyler çağrıştırmak",
    "scared to death": "ödü patlamak",
    "skeleton in the closet": "gizli ayıp / aile sırrı",
    "smell a rat": "işin içinde bir bit yeniği olduğunu sezmek",
    "speak of the devil": "iti an çomağı hazırla (lafın üstüne gelmek)",
    "take someone for a ride": "birini işletmek / kazıklamak",
    "the apple of someone's eye": "birinin göz bebeği",
    "the cold shoulder": "soğuk davranma",
    "the early bird catches the worm": "erken kalkan yol alır",
    "to be in the dark": "habersiz olmak",
    "to be on cloud nine": "bulutların üzerinde olmak (mutluluktan)",
    "to cost an arm and a leg": "bir servete mal olmak",
    "to cut a long story short": "uzun lafın kısası",
    "to feel under the weather": "halsiz hissetmek",
    "to get the hang of something": "bir şeyin püf noktasını kapmak",
    "to go from bad to worse": "kötüden daha kötüye gitmek",
    "to hit the sack": "kafa vurup yatmak",
    "to keep something under wraps": "bir şeyi gizli tutmak",
    "to make a long story short": "uzun lafın kısası",
    "to make both ends meet": "iki yakasını bir araya getirmek",
    "to pull someone's leg": "birisiyle kafa bulmak",
    "to put one's cards on the table": "açık oynamak / kartlarını açık oynamak",
    "to see eye to eye": "aynı fikirde olmak",
    "to take into account": "göz önünde bulundurmak",
    "to take part in": "yer almak / katılmak",
    "to throw in the towel": "havlu atmak / pes etmek",
    "under one's breath": "alçak sesle / mirildanarak",
    "up-to-date": "güncel / modaya uygun",
    "watch out": "dikkatli olmak",
    "wear one's heart on one's sleeve": "niyetini / duygularını belli etmek",
    "when pigs fly": "çıkmaz ayın son çarşambası / asla",
    "zero in on": "odaklanmak / hedefe kilitlenmek"
};
